/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package example.userGr;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author evgeniy.kozinov
 */
public class MyPaint extends javax.swing.JPanel {

    double q1 = 0;
    double q2 = 0;

  public void setQ1(double q1) {
    this.q1 = (pi / 180) * q1;
    repaint();
  }

  public void setQ2(double q2) {
    this.q2 = (pi / 180) * q2;
    repaint();
  }
    
    
    
  
    /** Creates new form MyPaint */
    public MyPaint() {
        initComponents();
        setQ1(30);
        setQ2(-20);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  double pi = 3.1415926535897932384626433832795;
  
  @Override
  protected void paintComponent(Graphics g) {
    super.paintComponent(g); 
    
    Graphics2D g2d = (Graphics2D)g;
    
    int w = getWidth();
    int h = getHeight();
   
    
    g2d.translate(w / 2, h / 2);
    
    g2d.scale(1, -1);
    
    //g2d.rotate(pi);
    
    g2d.setStroke(new BasicStroke(3));

    g2d.setColor(Color.black);
    g2d.drawLine(-w, 0, w, 0);
    g2d.drawLine(0, -h, 0, h);
   

    g2d.setColor(Color.red);
  
//    g2d.drawRoundRect(10, 50, 10, 10, 10, 10);
  
    g2d.drawRect(-5, -10, 10, 20);
    g2d.drawRoundRect(-5, -5, 10, 10, 10, 10);
    
    g2d.rotate(q1);
    g2d.drawLine(0, 0, 100, 0);
    g2d.translate(100, 0);
    g2d.drawRoundRect(-5, -5, 10, 10, 10, 10);

    g2d.rotate(q2);
    g2d.drawLine(0, 0, 100, 0);
    g2d.translate(100, 0);
    g2d.drawRoundRect(-5, -5, 10, 10, 10, 10);
    
  }

    
  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}
